### ISSUE TITLE
Let windowck plugin skip whiskermenu

### ISSUE THREAD

**Issue by FedeDP** [cedl38/xfce4-windowck-plugin#5]
Hi!
I'm trying out whiskermenu plugin, and i noticed that windowck plugin will display title and buttons as if whiskermenu was a normal window, but it shouldn't i guess.
Is there a way to let windowck skip this menu?
![istantanea - 19112013 - 22 52 05](https://f.cloud.github.com/assets/5837210/1576965/1e35ed7e-5164-11e3-9427-128b9949b9cb.png)

**Comment by cedl38** [comment]
Finally, I do not want to change this at the moment.  "Track active window" option should track the active window and Wiskermenu is considerered as the active window by wm. If I ignore it, the plugin will not found any active window and that can make things a litle confusing for me.

**Comment by milos3** [comment]
Yes, Wisker Menu is indeed considered an active window, but as I said before it's not a normal window but rather a sticky window. Sticky windows don't have minimize, maximize and close buttons therefore Window Header - Buttons should definitely skip sticky windows such as Whisker Menu, Guake drop down terminal, Notes (xfce4-notes) and so on, because using them can cause wierd actions with the sticky window. Now, for Window Header - Title I don't see a problem it displaying sticky window titles so they can stay as is.

So do reconsider and keep up with the good work, I really enjoy your plugin!
